const getVideoMetaIndex = require('./src/get-video-meta-index');
const peelMetaStream = require('./src/peel-meta-stream');
const parseMetaFile = require('./src/parse-meta-file');

const META_TYPE = 'gpmd';
const VIDEO_INPUT = './data/01.MP4';
const META_OUTPUT = './gps-data/01.bin';
(async () => {
  const videoMetaIndex = await getVideoMetaIndex(VIDEO_INPUT, META_TYPE);
  console.log(`Meta stream found at index ${videoMetaIndex}`);
  console.log(`Starting ffmpeg command to peel metadata from video ${VIDEO_INPUT}`);

  await peelMetaStream(VIDEO_INPUT, videoMetaIndex, META_OUTPUT);
  console.log('Gps stream generated by ffmpeg file is ready to be parsed');

  await parseMetaFile(META_OUTPUT);

  console.log('This is the end ...');
})();

// https://github.com/gopro/gpmf-parser/blob/master/GPMF_parser.c
// https://github.com/gopro/gpmf-parser/blob/master/GPMF_parser.h
// https://github.com/gopro/gpmf-parser
